package utils

import "strings"

func GetExtensionFromMime(mimeType string) string {
	switch strings.ToLower(strings.TrimSpace(mimeType)) {
	case "application/pdf":
		return ".pdf"
	case "application/msword":
		return ".doc"
	case "application/vnd.openxmlformats-officedocument.wordprocessingml.document":
		return ".docx"
	case "application/vnd.ms-excel":
		return ".xls"
	case "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":
		return ".xlsx"
	case "application/vnd.ms-powerpoint":
		return ".ppt"
	case "application/vnd.openxmlformats-officedocument.presentationml.presentation":
		return ".pptx"
	case "text/plain":
		return ".txt"
	case "text/csv":
		return ".csv"
	case "text/html":
		return ".html"
	case "application/rtf":
		return ".rtf"
	case "application/epub+zip":
		return ".epub"
	case "application/x-abiword":
		return ".abw"
	case "image/jpeg":
		return ".jpg"
	case "image/png":
		return ".png"
	case "image/gif":
		return ".gif"
	case "image/webp":
		return ".webp"
	case "image/bmp":
		return ".bmp"
	case "image/svg+xml":
		return ".svg"
	case "image/tiff":
		return ".tiff"
	case "image/x-icon":
		return ".ico"
	case "image/heic":
		return ".heic"
	case "audio/mpeg":
		return ".mp3"
	case "audio/wav":
		return ".wav"
	case "audio/ogg":
		return ".ogg"
	case "audio/webm":
		return ".weba"
	case "audio/aac":
		return ".aac"
	case "audio/flac":
		return ".flac"
	case "audio/x-ms-wma":
		return ".wma"
	case "video/mp4":
		return ".mp4"
	case "video/webm":
		return ".webm"
	case "video/x-msvideo":
		return ".avi"
	case "video/x-ms-wmv":
		return ".wmv"
	case "video/ogg":
		return ".ogv"
	case "video/mpeg":
		return ".mpeg"
	case "video/quicktime":
		return ".mov"
	case "video/3gpp":
		return ".3gp"
	case "application/zip":
		return ".zip"
	case "application/x-7z-compressed":
		return ".7z"
	case "application/x-rar-compressed":
		return ".rar"
	case "application/x-tar":
		return ".tar"
	case "application/gzip":
		return ".gz"
	case "application/x-bzip2":
		return ".bz2"
	case "application/javascript":
		return ".js"
	case "application/json":
		return ".json"
	case "text/css":
		return ".css"
	case "application/xml":
		return ".xml"
	case "application/x-sh":
		return ".sh"
	case "application/x-python":
		return ".py"
	case "application/x-httpd-php":
		return ".php"
	case "text/x-java-source":
		return ".java"
	case "text/x-c":
		return ".c"
	case "text/x-c++":
		return ".cpp"
	case "text/x-go":
		return ".go"
	case "text/markdown":
		return ".md"
	case "font/otf":
		return ".otf"
	case "font/ttf":
		return ".ttf"
	case "application/vnd.ms-fontobject":
		return ".eot"
	case "application/font-woff":
		return ".woff"
	case "application/font-woff2":
		return ".woff2"
	case "application/x-www-form-urlencoded":
		return ".urlencoded"
	case "multipart/form-data":
		return ".form"
	case "application/graphql":
		return ".graphql"
	case "application/x-yaml", "text/yaml":
		return ".yaml"
	case "application/x-protobuf":
		return ".proto"
	case "application/x-msgpack":
		return ".msgpack"
	case "application/octet-stream":
		return ".bin"
	case "application/x-dosexec":
		return ".exe"
	case "application/x-msdownload":
		return ".msi"
	case "application/vnd.android.package-archive":
		return ".apk"
	case "application/x-iso9660-image":
		return ".iso"
	case "application/x-img":
		return ".img"
	case "application/vnd.apple.installer+xml":
		return ".mpkg"
	case "message/rfc822":
		return ".eml"
	case "text/calendar":
		return ".ics"
	case "application/edraw":
		return ".eddx"
	case "application/drawio":
		return ".drawio"
	default:
		return ".bin"
	}
}
